### ISSUE TITLE
microservices inside - not up to date 

### ISSUE THREAD

**Issue by DanielPretzsch** [SAP/iot-application-services-sdk-nodejs#14]
A lot has happened around the APIs over the last few weeks. 
Unfortunately the project is not up to date with the latest Microservices.
Please update the project accordingly. (i miss, for example:  "config-thing-sap")

I don't like to make changes in the source code of you

Thanks

**Comment by sapjr** [comment]
Hi @DanielPretzsch ,

You're right, the micro service list is not up to date. But you can set the second parameter of the method to false, which disables the micro service check.
`setBaseUrl("config-thing-sap", false)`
This should do it.

Regards
Jan
