### ISSUE TITLE
What is 'appiot-mds'?

### ISSUE THREAD

**Issue by woodyjon** [SAP/iot-application-services-sdk-nodejs#16]
Hello,

Thanks for this SDK.
Could you please explain what is 'appiot-mds'?
You mention in the readme that it is the "the app of the API we will use in the following". But I do not understand what you mean there? Do we need to leave 'appiot-mds' as is or do we need to replace it with a name of a component of our system?

Thank you!

**Comment by sapjr** [comment]
Hi woodyjon,

Leonardo IoT consists of multiple micro services. You can find all of them in the documentation: https://help.sap.com/viewer/080fabc6cae6423fb45fca7752adb61e/1906a/en-US/dcaa38dda9e14fbc887a3ebda36aec98.html
‘appiot-mds’ is one of those micro services. It depends on what you want to do which micro service you have to pass as an argument in this method.

Regards
Jan
